const information = [
{
    name: "Psychic Game",
    appLink: "https://illimitableissi.github.io/Psychic-Game",
    gitHub: "https://github.com/illimitableissi/Psychic-Game.git",
    imgSrc: "images/placeholder1.jpg",
    message: "The app randomly picks a letter, and the user has to guess which letter the app chose.",
},
{
    name: "Crystal Collector",
    appLink: "https://illimitableissi.github.io/unit-4-game/",
    gitHub: "https://github.com/illimitableissi/unit-4-game.git",
    imgSrc: "images/placeholder2.jpg",
    message: "The app randomly picks a number and the user will have to click on the stones and match the number.",
},
{
    name: "Dragon Ball Trivia!",
    appLink: "https://illimitableissi.github.io/TriviaGame/",
    gitHub: "https://github.com/illimitableissi/TriviaGame.git",
    imgSrc: "images/placeholder3.jpg",
    message: "Dragon Ball Series trivia game.",
},
{
    name: "One Piece Pirates!",
    appLink: "https://illimitableissi.github.io/GifTastic/",
    gitHub: "https://github.com/illimitableissi/GifTastic.git",
    imgSrc: "images/placeholder4.jpg",
    message: "User can click on a character name and gifs will populate from the GIPHY API.",
},
{
    name: "Train Scheduler",
    appLink: "https://illimitableissi.github.io/TrainScheduler/",
    gitHub: "https://github.com/illimitableissi/TrainScheduler.git",
    imgSrc: "images/placeholder6.jpg",
    message: "Incorporates Firebase to host arrival and departure data. This website will provide up-to-date information about various trains, namely their arrival times and how many minutes remain until they arrive at their station.",
},
{
    name: "TraveLite",
    appLink: "https://usafowose.github.io/Project-1/",
    gitHub: "https://github.com/usafowose/Project-1.git",
    imgSrc: "images/placeholder7.jpg",
    message: "Users can enter flight information and will be shown various flights, weather forecasts, and images of their chosen location.",
},
{
    name: "LIRI Bot-Node.js",
    appLink: "#",
    gitHub: "https://github.com/illimitableissi/liri-node-app.git",
    imgSrc: "images/placeholder10.jpg",
    message: "Node app that allows users to see movie information, concerts, and music information from various APIs.",
},
{
    name: "MySQL+Node.js Bamazon",
    appLink: "#",
    gitHub: "https://github.com/illimitableissi/bamazon.git",
    imgSrc: "images/placeholder11.jpg",
    message: "Back-end storefront built with MySQL.",
},
{
    name: "Friend Finder",
    appLink: "https://friend-finderi.herokuapp.com/",
    gitHub: "https://github.com/illimitableissi/FriendFinder.git",
    imgSrc: "images/placeholder12.jpg",
    message: "This full-stack site will take in results from your users' surveys, then compare their answers with those from other users. The app will then display the name and picture of the user with the best overall match.",
},
{
    name: "Eat Da Burger!",
    appLink: "https://burgerii.herokuapp.com/",
    gitHub: "https://github.com/illimitableissi/burger",
    imgSrc: "images/placeholder13.jpg",
    message: "Restaurant app that lets users input the names of burgers they'd like to eat.",
},
{
    name: "The Krusty Krab<",
    appLink: "https://thekrustykrab.herokuapp.com/",
    gitHub: "https://github.com/illimitableissi/Project-2",
    imgSrc: "images/placeholder14.jpg",
    message: "Spongebob Squarepants themed restaurant app.",
},
{
    name: "Clicky Game",
    appLink: "https://illimitableissi.github.io/React-Clicky-Game/",
    gitHub: "https://github.com/illimitableissi/React-Clicky-Game.git",
    imgSrc: "images/placeholder15.jpg",
    message: "Click Game made through React.js",
},
{
    name: "",
    appLink: "",
    gitHub: "",
    imgSrc: "",
    message: "",
},
{
    name: "",
    appLink: "",
    gitHub: "",
    imgSrc: "",
    message: "",
},
{
    name: "",
    appLink: "",
    gitHub: "",
    imgSrc: "",
    message: "",
},

]

export default information